import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

const API_BASE = "https://resume-ats-analyzer-without-login.applypilot.us";

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();

        const response = await fetch(`${API_BASE}/api/download-report`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify(body),
        });

        if (!response.ok) {
            return NextResponse.json(
                { detail: "Failed to generate report" },
                { status: response.status }
            );
        }

        const pdfBuffer = await response.arrayBuffer();

        // Rebrand the PDF — replace original branding with ApplyPilot
        const pdfDoc = await PDFDocument.load(pdfBuffer);
        const pages = pdfDoc.getPages();
        const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
        const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

        // The original branding appears at the bottom of the last page
        // We cover it with a white rectangle and overlay ApplyPilot branding
        const lastPage = pages[pages.length - 1];
        const { width } = lastPage.getSize();

        // Cover the bottom ~60px of the last page (where original branding sits)
        lastPage.drawRectangle({
            x: 0,
            y: 0,
            width: width,
            height: 60,
            color: rgb(1, 1, 1), // white background
        });

        // Add ApplyPilot branding
        const brandText = "Generated by ApplyPilot — AI-Powered Job Application Automation";
        const brandTextWidth = font.widthOfTextAtSize(brandText, 9);
        lastPage.drawText(brandText, {
            x: (width - brandTextWidth) / 2,
            y: 35,
            size: 9,
            font: fontBold,
            color: rgb(0.3, 0.3, 0.3),
        });

        const urlText = "https://applypilot.us | contact@applypilot.us";
        const urlTextWidth = font.widthOfTextAtSize(urlText, 8);
        lastPage.drawText(urlText, {
            x: (width - urlTextWidth) / 2,
            y: 20,
            size: 8,
            font: font,
            color: rgb(0.5, 0.5, 0.5),
        });

        // Also check all pages for any footer branding and cover them
        for (const page of pages) {
            const { width: pageWidth } = page.getSize();

            // Cover the very bottom of every page (in case there's a footer)
            if (page !== lastPage) {
                page.drawRectangle({
                    x: 0,
                    y: 0,
                    width: pageWidth,
                    height: 30,
                    color: rgb(1, 1, 1),
                });

                const pageFooter = "ApplyPilot — applypilot.us";
                const pageFooterWidth = font.widthOfTextAtSize(pageFooter, 7);
                page.drawText(pageFooter, {
                    x: (pageWidth - pageFooterWidth) / 2,
                    y: 12,
                    size: 7,
                    font: font,
                    color: rgb(0.6, 0.6, 0.6),
                });
            }
        }

        const modifiedPdf = await pdfDoc.save();

        return new NextResponse(modifiedPdf, {
            status: 200,
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": 'attachment; filename="ats-resume-report.pdf"',
            },
        });
    } catch (error) {
        console.error("ATS download report error:", error);
        return NextResponse.json(
            { detail: "Internal server error while generating report" },
            { status: 500 }
        );
    }
}
